version: '3.1'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:7.2
    container_name: php-covid-19
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: php-app
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - /var/www/vendor
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini      
    networks:
      - app-network

  # #Nginx Service For Development Only
  # webserver:
  #   image: nginx:alpine
  #   container_name: webserver-covid-19
  #   restart: unless-stopped
  #   tty: true
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./:/var/www
  #     - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
  #     - ./docker/nginx/certs/:/etc/nginx/certs/
  #   networks:
  #     - app-network


  #Node Service For Development Only
  node:
    image: node:10
    container_name: node-covid-19
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - /var/www/node_modules
    ports: 
      - "9058:9058"
    command: "tail -f /dev/null"
    networks:
      - app-network

  

#Docker Networks
networks:
  app-network:
    driver: bridge
